CREATE DATABASE YOUCODECLUBS;
USE YOUCODECLUBS;
CREATE TABLE ADMIN(
	Id INT NOT NULL PRIMARY KEY auto_increment,
    FName VARCHAR(255),
    LName VARCHAR(255),
    Password VARCHAR(255)
);

CREATE TABLE USER(
	Id INT NOT NULL PRIMARY KEY auto_increment,
    FName VARCHAR(255),
    LName VARCHAR(255),
    Password VARCHAR(255)
);

CREATE TABLE CLUBS(
	Name VARCHAR(255),
    Description VARCHAR(255),
	Image varchar(255)
);

ALTER TABLE USER
ADD Image VARCHAR(255);

ALTER TABLE ADMIN
ADD Image VARCHAR(255);

SELECT * FROM ADMIN;

